#!/bin/bash

set -euxo pipefail

git grep -l -F "$1" -- "$3" | php -r 'while (false !== $s = fgets(STDIN)) { $p = rtrim($s, "\n"); $c = file_get_contents($p); $c = str_replace($argv[1], $argv[2], $c); file_put_contents($p, $c); }' "$1" "$2"
